_wandb:
    value:
        cli_version: 0.19.8
        code_path: code/train_custom_carracing.py
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.9.21
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
K_epochs:
    value: 40
action_std_init:
    value: 0.6
encoder_dim:
    value: 512
env_name:
    value: CustomCarRacingEasy-v0
eps_clip:
    value: 0.2
gamma:
    value: 0.99
has_continuous_action_space:
    value: false
lr_actor:
    value: 0.0003
lr_critic:
    value: 0.001
random_seed:
    value: 42
update_timestep:
    value: 4000
